"""Streamlit UI: the only thing the end user actually sees.

Single page, four states:

1. Empty — show the drag-drop uploader and a one-liner about what to drop.
2. Uploaded but not started — show the preflight panel and a "Start" button.
3. Training — show the live dashboard (progress, loss/PSNR charts, preview,
   intermediate-ply downloads).
4. Done / failed — show the final download (or error) and a "submit another"
   button.

The page never asks the user to touch the command line or a config file.
The only optional control is the **Quality** preset dropdown (Auto / Maximum).
"""
from __future__ import annotations

import os
import shutil
import tempfile
from pathlib import Path

import streamlit as st

from gs_pipeline.ui.live_view import render_live_dashboard
from gs_pipeline.ui.preflight import (
    PreflightReport,
    estimate_training_minutes,
    run_preflight,
)

PAGE_TITLE = "gs_pipeline — Metashape → Gaussian Splat"
DEFAULT_WORK_ROOT = Path(os.environ.get("GS_WORK", "/data/work"))
DEFAULT_INBOX = Path(os.environ.get("GS_INBOX", "/data/inbox"))
DEFAULT_OUTBOX = Path(os.environ.get("GS_OUTBOX", "/data/outbox"))
MAX_UPLOAD_MB = int(os.environ.get("MAX_UPLOAD_GB", "8")) * 1024


def _init_state() -> None:
    st.session_state.setdefault("phase", "upload")
    st.session_state.setdefault("preflight", None)
    st.session_state.setdefault("uploaded_bundle_path", None)
    st.session_state.setdefault("job_id", None)


def _phase_upload() -> None:
    st.title(PAGE_TITLE)
    st.markdown(
        "Drag your Metashape export bundle (a `*_splat_bundle.zip`) into "
        "the area below. The trainer auto-tunes for your scene and GPU."
    )
    quality = st.selectbox(
        "Quality preset",
        options=["Auto", "Maximum"],
        index=0,
        help="`Auto` = 30k iterations, balanced quality/time. "
             "`Maximum` = 50k iterations, slightly more splats per scene.",
    )
    st.session_state["quality_preset"] = quality

    file = st.file_uploader(
        "Drop your bundle .zip here",
        type=["zip"],
        accept_multiple_files=False,
        help=f"Max {MAX_UPLOAD_MB / 1024:.0f} GB. Generated by the Metashape "
             f"`export_for_splat.py` script.",
    )
    if file is None:
        return

    upload_dir = Path(tempfile.mkdtemp(prefix="gs_upload_"))
    zip_path = upload_dir / file.name
    zip_path.write_bytes(file.getvalue())
    st.session_state["uploaded_bundle_path"] = str(zip_path)

    try:
        with st.spinner("Reading bundle and computing preflight…"):
            report = run_preflight(zip_path, quality_preset=quality)
    except Exception as exc:
        st.error(f"Bundle is not usable: {type(exc).__name__}: {exc}")
        return

    st.session_state["preflight"] = report
    st.session_state["phase"] = "preflight"
    st.rerun()


def _phase_preflight() -> None:
    report: PreflightReport = st.session_state["preflight"]
    quality: str = st.session_state.get("quality_preset", "Auto")
    st.title("Preflight summary")
    st.markdown(
        f"**{report.n_cameras} cameras** · **{report.total_megapixels:.1f} MP** "
        f"(after downscale) · dense cloud **{report.dense_pts_loaded:,}** pts "
        f"(downsampled to {report.dense_pts_after_downsample:,})"
    )
    mins = estimate_training_minutes(report.target_splats, report.iterations)
    st.markdown(
        f"Targeting **{report.target_splats / 1e6:.2f} M splats** "
        f"(hard cap {report.hard_cap_splats / 1e6:.1f} M on {report.gpu_name}). "
        f"Approximately **{mins:.0f} min** at the `{quality}` preset."
    )
    if report.image_max_side_orig > report.image_max_side:
        st.info(
            f"Photos longer than {report.image_max_side}px will be downscaled "
            f"by {report.downscale_factor:.2f} for training. Final eval and "
            f"the exported splat are still in full detail."
        )
    for w in report.warnings:
        st.warning(w)

    col_start, col_cancel = st.columns([2, 1])
    if col_start.button("Start training", type="primary", use_container_width=True):
        _start_training(report, quality)
    if col_cancel.button("Cancel", use_container_width=True):
        _reset()
        st.rerun()


def _phase_training() -> None:
    job_id = st.session_state["job_id"]
    js = render_live_dashboard(
        job_id=job_id, work_root=DEFAULT_WORK_ROOT,
    )
    st.divider()
    if js is not None and js.state.value in ("done", "failed"):
        if st.button("Submit another bundle"):
            _reset()
            st.rerun()


def _start_training(report: PreflightReport, quality: str) -> None:
    """Move the uploaded zip into the inbox so the watcher picks it up.

    We don't run the trainer in-process — the watcher (a separate process)
    sees the new file, claims it (rename to ``claim__<id>__name.zip``), and
    invokes ``pipeline.run_job`` as a subprocess. The UI then transitions to
    the training phase and starts polling state.json.
    """
    zip_path = Path(st.session_state["uploaded_bundle_path"])
    DEFAULT_INBOX.mkdir(parents=True, exist_ok=True)
    target = DEFAULT_INBOX / zip_path.name
    if target.exists():
        # Avoid clobbering an existing job's zip; suffix with a counter.
        i = 1
        while (DEFAULT_INBOX / f"{zip_path.stem}_{i}.zip").exists():
            i += 1
        target = DEFAULT_INBOX / f"{zip_path.stem}_{i}.zip"
    shutil.move(str(zip_path), str(target))
    # The watcher will rename to claim__<id>__name.zip; we discover the id
    # by polling inbox/ for that prefix on the live dashboard.
    st.session_state["expected_bundle_name"] = target.name
    st.session_state["job_id"] = _wait_for_job_id(target.name)
    st.session_state["phase"] = "training"
    st.rerun()


def _wait_for_job_id(bundle_name: str, *, timeout_s: float = 30.0) -> str:
    """Block briefly until the watcher renames our zip to claim__<id>__name.zip.

    Returns the id, or a placeholder so the dashboard still polls.
    """
    import time
    from gs_pipeline.trainer.watcher import CLAIM_PREFIX, _job_id_from_claim
    deadline = time.monotonic() + timeout_s
    while time.monotonic() < deadline:
        for p in DEFAULT_INBOX.glob(f"{CLAIM_PREFIX}*__{bundle_name}"):
            return _job_id_from_claim(p)
        time.sleep(0.5)
    return "pending"


def _reset() -> None:
    for key in ("phase", "preflight", "uploaded_bundle_path", "job_id"):
        st.session_state[key] = None
    st.session_state["phase"] = "upload"


def main() -> None:
    st.set_page_config(page_title=PAGE_TITLE, page_icon=":milky_way:", layout="wide")
    _init_state()
    phase = st.session_state["phase"]
    if phase == "upload":
        _phase_upload()
    elif phase == "preflight":
        _phase_preflight()
    elif phase == "training":
        _phase_training()
    else:
        _reset()
        st.rerun()


if __name__ == "__main__" or True:
    # Streamlit invokes the script top-to-bottom on every interaction; the
    # `or True` ensures main() runs even when Streamlit imports the module
    # without executing `__main__`. Idempotent in all phases.
    main()
